// <auto-generated />
using System;
using Melarium.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Melarium.Entity.Migrations
{
    [DbContext(typeof(MelariumDbContext))]
    [Migration("20260424101436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Melarium.Domain.Entities.Apiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Apiaries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mountain apiary located near the forest edge, known for acacia and linden honey.",
                            Name = "Gorska Pčelinja",
                            OrganizationId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Valley farm apiary with diverse flora — clover, sunflower, and wildflower.",
                            Name = "Dolinska Farma",
                            OrganizationId = 1
                        });
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Beehive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Material")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("QrCodeBase64")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasFilter("\"UniqueId\" IS NOT NULL");

                    b.ToTable("Beehives", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiaryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Material = 1,
                            Name = "Košnica A1",
                            Notes = "Strong colony, productive queen introduced spring 2023.",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            ApiaryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Material = 1,
                            Name = "Košnica A2",
                            Notes = "Newer colony, monitoring for development.",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            ApiaryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Material = 3,
                            Name = "Košnica B1",
                            Notes = "Insulated polystyrene hive — excellent for winter survival.",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            ApiaryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Material = 1,
                            Name = "Košnica B2",
                            Notes = "Warré hive added for natural beekeeping trial.",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeehiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("CustomFoodType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("EarlyCompletionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FoodType")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeehiveId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Diets", (string)null);
                });

            modelBuilder.Entity("Melarium.Domain.Entities.FeedingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DietId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DietId");

                    b.HasIndex("ScheduledDate");

                    b.ToTable("FeedingEntries", (string)null);
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeehiveId")
                        .HasColumnType("integer");

                    b.Property<string>("BroodStatus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoneyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeehiveId");

                    b.HasIndex("Date");

                    b.ToTable("Inspections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeehiveId = 1,
                            BroodStatus = "Healthy brood pattern. Queen spotted. Eggs and larvae present.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoneyLevel = 3,
                            Notes = "Colony strong. Added super for honey storage.",
                            Temperature = 22.5
                        },
                        new
                        {
                            Id = 2,
                            BeehiveId = 1,
                            BroodStatus = "Good brood. Some drone cells observed.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoneyLevel = 2,
                            Notes = "Honey super 60% full. Will harvest next visit.",
                            Temperature = 28.0
                        },
                        new
                        {
                            Id = 3,
                            BeehiveId = 2,
                            BroodStatus = "Sparse brood. Queen activity low.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoneyLevel = 1,
                            Notes = "Consider requeening if no improvement in 3 weeks.",
                            Temperature = 21.0
                        },
                        new
                        {
                            Id = 4,
                            BeehiveId = 3,
                            BroodStatus = "Improving brood pattern. Queen productive.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoneyLevel = 2,
                            Notes = "Colony recovering well.",
                            Temperature = 25.5
                        });
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A family-run beekeeping operation in the lowlands, specialising in wildflower honey.",
                            Name = "Golden Hive Co"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-altitude apiculture collective producing premium acacia and linden honey.",
                            Name = "Mountain Bees"
                        });
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<int?>("BeehiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("BeehiveId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Todos", (string)null);
                });

            modelBuilder.Entity("Melarium.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Apiary", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Melarium.Domain.Entities.Organization", "Organization")
                        .WithMany("Apiaries")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Beehive", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.Apiary", "Apiary")
                        .WithMany("Beehives")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Melarium.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Apiary");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Diet", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.Beehive", "Beehive")
                        .WithMany("Diets")
                        .HasForeignKey("BeehiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Melarium.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beehive");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.FeedingEntry", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.Diet", "Diet")
                        .WithMany("FeedingEntries")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Inspection", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.Beehive", "Beehive")
                        .WithMany("Inspections")
                        .HasForeignKey("BeehiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beehive");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Organization", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Todo", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.Apiary", "Apiary")
                        .WithMany()
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Melarium.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Melarium.Domain.Entities.Beehive", "Beehive")
                        .WithMany()
                        .HasForeignKey("BeehiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Melarium.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Apiary");

                    b.Navigation("AssignedTo");

                    b.Navigation("Beehive");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.User", b =>
                {
                    b.HasOne("Melarium.Domain.Entities.Apiary", "Apiary")
                        .WithMany()
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Melarium.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Apiary");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Apiary", b =>
                {
                    b.Navigation("Beehives");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Beehive", b =>
                {
                    b.Navigation("Diets");

                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Diet", b =>
                {
                    b.Navigation("FeedingEntries");
                });

            modelBuilder.Entity("Melarium.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Apiaries");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
